# Generated by Django 5.0.3 on 2024-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0009_loan_amount_paid_till_date_loan_loan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
